import {initSettings,readSettings,readFooterSettings,setSettingsBusy} from './settings-ui.js';
import {pickMissingStations} from './station-picker.js';
import {processImage} from './process.js';
const $=id=>document.getElementById(id);let busy=false,resultBlob=null,resultURL=null,workerPromise=null,stage='';
initSettings();
function status(text,p,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);if(p!==undefined)$('progress').value=p;}
async function getWorker(){if(!window.Tesseract)throw Error('识别组件未能加载，请刷新页面后重试。');if(!workerPromise)workerPromise=Tesseract.createWorker('chi_sim+eng',1,{workerPath:new URL('vendor/worker.min.js',location.href).href,corePath:new URL('vendor/',location.href).href,langPath:new URL('vendor',location.href).href,logger:m=>{if(m.status==='loading language traineddata')status('首次使用，正在加载中文识别组件…');}}).catch(e=>{workerPromise=null;throw e});return workerPromise;}
async function run(blob){if(busy)throw Error('图片正在处理中，请稍候。');let rules,footer;try{rules=readSettings();footer=readFooterSettings();}catch(e){status(e.message,0,true);throw e;}busy=true;setSettingsBusy(true);resultBlob=null;$('file').disabled=true;$('demo').disabled=true;$('result').hidden=true;$('progress').hidden=false;status('正在读取图片…',2);let imageURL;try{if(blob.size>25*1024*1024)throw Error('图片超过25MB，请使用公司导出的PNG或JPG原图。');imageURL=URL.createObjectURL(blob);const img=new Image();img.src=imageURL;await img.decode();const worker=await getWorker();const r=await processImage(img,worker,(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c},(p,s)=>status(s,p),rules,pickMissingStations,footer);resultBlob=await new Promise(resolve=>r.canvas.toBlob(resolve,'image/png'));if(!resultBlob)throw Error('图片生成失败，请重试。');if(resultURL)URL.revokeObjectURL(resultURL);resultURL=URL.createObjectURL(resultBlob);$('output').src=resultURL;$('result').hidden=false;$('badge').textContent=`${r.highlighted}个站已突出显示`;$('changes').textContent=r.updates.map(u=>`${(u.from/100).toFixed(2)} → ${(u.to/100).toFixed(2)} 元/升（${u.count}个站）`).join('；')+`。${r.merged?'已合并'+r.merged+'个同价栏。':'本次没有同价栏需要合并。'}`;$('changes').textContent+=(r.missing.length?' 未找到，已跳过：'+r.missing.join('、')+'。请核对站名或原图清晰度。':'');if(r.footerWarning)$('changes').textContent+=' '+r.footerWarning;status('已生成高清图片，下滑预览并保存。',100);return {changedBands:r.updates,mergedBands:r.merged,stations:r.stationCount};}catch(e){status(e.message||'处理失败，请换用清晰的完整原图。',0,true);throw e;}finally{if(imageURL)URL.revokeObjectURL(imageURL);busy=false;setSettingsBusy(false);$('file').disabled=false;$('demo').disabled=false;$('progress').hidden=true;}}
$('file').addEventListener('change',()=>{const f=$('file').files[0];if(f)run(f).catch(()=>{});$('file').value='';});
$('demo').addEventListener('click',async()=>{try{const r=await fetch('example.png');if(!r.ok)throw Error('示例加载失败，请稍后重试。');await run(await r.blob())}catch(e){status(e.message,0,true)}});
$('save').addEventListener('click',async()=>{if(!resultBlob)return;const file=new File([resultBlob],`泸州油价-${new Date().toLocaleDateString('sv-SE')}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'泸州柴油价目图'});return}catch(e){if(e.name==='AbortError')return;}}const a=document.createElement('a');a.href=resultURL;a.download=file.name;document.body.append(a);a.click();a.remove();});
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'process_example_oil_price_image',title:'处理示例油价图',description:'使用页面提供的公司原图，执行整栏调价并在页面显示可保存的图片。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受额外参数');const r=await fetch('example.png');if(!r.ok)throw Error('示例加载失败');return run(await r.blob());}})).catch(()=>{})}catch{}}
