export const TARGETS=['泸渝高速合江服务区南/北','泸州龙马潭安宁','泸州龙马潭临港','泸州兆雅加油站'];
export const normalize=s=>s.replace(/[\s，,。．:：!！()（）]/g,'').replaceAll('沪','泸').replaceAll('潭','滩');
export function targetIndex(s){let n=normalize(s);if(n.includes('合江')&&n.includes('服务'))return 0;if(n.includes('龙马')&&n.includes('安宁'))return 1;if(n.includes('龙马')&&n.includes('临港'))return 2;if((n.includes('兆雅')||n.includes('兆推'))&&n.includes('加油'))return 3;return -1;}
export function priceFromText(s){const t=s.replace(/[\s,，]/g,'').replace(/[。．]/g,'.');const m=t.match(/优惠[^0-9]*([0-9]+\.[0-9]{1,2})元?.*结[算笪看]价?[^0-9]*([0-9]+\.[0-9]{1,2})/);if(!m)return null;return {discount:Math.round(Number(m[1])*100),price:Math.round(Number(m[2])*100)};}
export function adjustBands(bands,delta=5){const found=new Set();const updates=[];const adjusted=bands.map(b=>{const ids=b.stations.filter(s=>s.target>=0).map(s=>s.target);ids.forEach(i=>found.add(i));const changed=ids.length>0;const price=b.price+(changed?delta:0);const discount=b.discount-(changed?delta:0);if(discount<0)throw Error('调价后优惠为负数，请核对原图。');if(changed)updates.push({from:b.price,to:price,targets:ids});return {...b,price,discount,changed,stations:[...b.stations]}});if(found.size!==4)throw Error('未完整识别四个重点站，请使用公司导出的清晰原图。');const merged=new Map();for(const b of adjusted){if(merged.has(b.price)){const g=merged.get(b.price);if(g.discount!==b.discount)throw Error('相同结算价的优惠金额不一致，请核对原图。');g.stations.push(...b.stations);g.changed||=b.changed;}else merged.set(b.price,{...b});}const groups=[...merged.values()].sort((a,b)=>a.price-b.price);for(const g of groups)g.stations.sort((a,b)=>(a.target<0?99:a.target)-(b.target<0?99:b.target));return {groups,updates,merged:bands.length-groups.length};}
export function detectBands(image){const {width:w,height:h,data:d}=image;const colorAt=y=>{const colors=[];for(const f of [.009,.019,.981,.991]){const x=Math.min(w-1,Math.floor(w*f));const i=(y*w+x)*4;colors.push([d[i],d[i+1],d[i+2]])}return [0,1,2].map(k=>colors.map(c=>c[k]).sort((a,b)=>a-b)[2])};const dist=(a,b)=>Math.max(...a.map((v,i)=>Math.abs(v-b[i])));const segments=[];let start=0,color=colorAt(0);for(let y=1;y<h;y++){const next=colorAt(y);if(dist(next,color)>18){if(y-start>=Math.max(12,h*.006))segments.push({y:start,end:y,color});start=y;color=next;}}if(h-start>=12)segments.push({y:start,end:h,color});return segments.filter(s=>Math.max(...s.color)-Math.min(...s.color)>10);}
export function inkRows(image,band){const {width:w,data:d}=image;let runs=[],start=-1;for(let y=band.y+2;y<band.end-1;y++){let count=0;for(let x=6;x<w-6;x++){let i=(y*w+x)*4;if(Math.max(d[i],d[i+1],d[i+2])<135)count++;}const active=count>Math.max(5,w*.004);if(active&&start<0)start=y;if(!active&&start>=0){if(y-start>2)runs.push({y:start,end:y});start=-1;}}if(start>=0)runs.push({y:start,end:band.end-1});const merged=[];for(const r of runs){const last=merged.at(-1);if(last&&r.y-last.end<Math.max(3,w*.003)){last.end=r.end}else merged.push({...r})}return merged.filter(r=>r.end-r.y>=w*.008);}
export function inkBox(image,x0,y0,x1,y1){const {width:w,data:d}=image;let l=x1,r=x0,t=y1,b=y0,count=0;for(let y=Math.max(0,Math.floor(y0));y<Math.min(image.height,y1);y++)for(let x=Math.max(0,Math.floor(x0));x<Math.min(w,x1);x++){const i=(y*w+x)*4;if(Math.max(d[i],d[i+1],d[i+2])<135){l=Math.min(l,x);r=Math.max(r,x+1);t=Math.min(t,y);b=Math.max(b,y+1);count++;}}return count>12?{x:l,y:t,w:r-l,h:b-t}:null;}
export function cellsForBand(image,band,rows){const w=image.width;let cells=[];const single=rows.length===1;let priceColumn=1;if(single){const right=inkBox(image,w*2/3,rows[0].y,w,rows[0].end);if(right&&right.w>w*.2)priceColumn=2;}for(let col=0;col<3;col++)for(let row=0;row<rows.length;row++){if(row===rows.length-1&&(!single||col===priceColumn))continue;const r=rows[row];const box=inkBox(image,Math.ceil(w*col/3)+3,r.y,Math.floor(w*(col+1)/3)-3,r.end);if(box)cells.push({box,target:-1});}return cells;}


