import {defaultRules,applyRules,stationRule} from './settings.js';
import {recoverStations,missingRules} from './station-recovery.js';
import {TARGETS,adjustBands,detectBands,inkRows,cellsForBand,priceFromText,targetIndex,normalize} from './engine.js';
import {ensureExportFont,EXPORT_FONT} from './export-font.js';
import {inkCoverage} from './raster.js';
export async function processImage(source,worker,canvasFactory,progress=()=>{},rules=defaultRules(),resolveMissing){
 const make=(w,h)=>canvasFactory(Math.ceil(w),Math.ceil(h)); const input=make(source.width,source.height);input.getContext('2d').drawImage(source,0,0);const image=input.getContext('2d').getImageData(0,0,input.width,input.height);const w=input.width;
 if(w<700||input.height/w<1.1)throw Error('请上传完整、清晰的竖版表格原图（宽度至少700像素）。');
 const regions=detectBands(image);if(regions.length<4)throw Error('未识别到彩色价格栏。当前版本适用于示例中的三列彩色表格。');
 const crop=(box,bw=false)=>{const c=make(box.w+20,box.h+20);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(input,box.x,box.y,box.w,box.h,10,10,box.w,box.h);if(bw){const d=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){let v=Math.max(d.data[i],d.data[i+1],d.data[i+2])<135?0:255;d.data[i]=d.data[i+1]=d.data[i+2]=v;d.data[i+3]=255;}ctx.putImageData(d,0,0);}return c;};
 const read=async(c,blocks=false)=>{const r=await worker.recognize(c.toDataURL('image/png'),{},blocks?{text:true,blocks:true}:{text:true});return r.data;};
 await worker.setParameters({tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'});
 const bands=[];let tailStart=null;for(let i=0;i<regions.length;i++){const region=regions[i];const rows=inkRows(image,region);if(!rows.length)throw Error('发现无法读取的彩色栏，请上传完整原图。');const last=rows.at(-1);progress(12+i/regions.length*28,'正在读取各栏价格…');const data=await read(crop({x:0,y:last.y-2,w,h:last.end-last.y+4},true));const p=priceFromText(data.text);if(!p){if(bands.length===0)throw Error('未能读清第一栏价格，请使用清晰的公司原图。');tailStart=region.y;break;}if(p.price<100||p.price>2000||p.discount<0||p.discount>500)throw Error('识别到异常价格，请更换清晰原图。');const stations=cellsForBand(image,region,rows);if(!stations.length)throw Error('未能分离站点与价格，请使用与示例相同格式的原图。');bands.push({...region,...p,stations});}
 if(bands.length<3||tailStart===null)throw Error('未识别到完整的价格表和底部说明，请上传完整原图。');
 // All listed tier prices must use the same posted-price anchor.
 const anchor=bands[0].price+bands[0].discount;if(bands.some(b=>b.price+b.discount!==anchor))throw Error('识别出的优惠与结算价不一致，已停止出图。请换一张清晰原图。');
 const stations=bands.flatMap(b=>b.stations.map(s=>{s.background=b.color;return s;}));const sheet=make(900,stations.length*72+20);const sctx=sheet.getContext('2d');sctx.fillStyle='white';sctx.fillRect(0,0,sheet.width,sheet.height);stations.forEach((s,i)=>{const c=crop(s.box,true);const scale=Math.min(46/c.height,860/c.width);sctx.drawImage(c,20,10+i*72,c.width*scale,c.height*scale);});
 progress(45,'正在识别需要修改的站点…');await worker.setParameters({tessedit_pageseg_mode:'6'});const stationData=await read(sheet,true);const texts=stations.map(()=>[]);for(const block of stationData.blocks||[])for(const para of block.paragraphs||[])for(const line of para.lines||[]){const i=Math.floor(((line.bbox.y0+line.bbox.y1)/2-10)/72);if(i>=0&&i<stations.length)texts[i].push(line.text);}
 stations.forEach((s,i)=>{s.text=texts[i].join('');s.target=targetIndex(s.text);});
 for(const s of stations.filter(s=>s.target<0&&normalize(s.text).includes('龙马'))){const c=crop(s.box,true),large=make(c.width*2,c.height*2);large.getContext('2d').drawImage(c,0,0,large.width,large.height);await worker.setParameters({tessedit_pageseg_mode:'7'});const retry=await read(large);s.target=targetIndex(retry.text);if(s.target>=0)s.text=TARGETS[s.target];}
 await recoverStations(stations,rules,async(s,mode)=>{
  const b=s.box,pad=3,x=Math.max(0,b.x-pad),y=Math.max(0,b.y-pad),cw=Math.min(w-x,b.w+2*pad),ch=Math.min(input.height-y,b.h+2*pad),c=make(cw,ch),cx=c.getContext('2d');cx.drawImage(input,x,y,cw,ch,0,0,cw,ch);const data=cx.getImageData(0,0,cw,ch);
  for(let i=0;i<data.data.length;i+=4){const coverage=inkCoverage(data.data[i],data.data[i+1],data.data[i+2],s.background)/255;const value=mode?(coverage>.36?0:255):Math.round(255*(1-coverage));data.data[i]=data.data[i+1]=data.data[i+2]=value;data.data[i+3]=255;}cx.putImageData(data,0,0);
  const scale=Math.max(2,Math.min(4,80/ch)),large=make(cw*scale+40,ch*scale+40),lc=large.getContext('2d');lc.fillStyle='white';lc.fillRect(0,0,large.width,large.height);lc.drawImage(c,20,20,cw*scale,ch*scale);await worker.setParameters({tessedit_pageseg_mode:mode?'13':'7'});return (await read(large)).text;
 },progress);
 const unresolved=missingRules(stations,rules);
 if(unresolved.length&&resolveMissing){
  const choices=stations.map((s,index)=>({index,text:s.text,image:crop(s.box).toDataURL('image/png'),price:bands.find(b=>b.stations.includes(s)).price}));
  const assignments=await resolveMissing(unresolved,choices,rules,stations);
  const used=new Set(),usedRules=new Set();for(const a of assignments){if(!unresolved.some(r=>r.index===a.rule)||!Number.isInteger(a.station)||!stations[a.station]||used.has(a.station)||usedRules.has(a.rule)||stationRule(stations[a.station],rules)>=0)throw Error('站点选择无效，请重新处理。');used.add(a.station);usedRules.add(a.rule);stations[a.station].confirmedName=rules[a.rule].name;}
 }
 const result=applyRules(bands,rules);
 progress(78,'正在核对底部说明…');const footerRegion=regions.at(-1);const footerRows=inkRows(image,footerRegion);const footerRow=footerRows.at(-1);if(!footerRow||footerRow.y<tailStart)throw Error('未能识别底部说明。');await worker.setParameters({tessedit_pageseg_mode:'7'});const footerData=await read(crop({x:0,y:footerRow.y-2,w,h:footerRow.end-footerRow.y+4},true));const footerText=normalize(footerData.text);const threshold=footerData.text.replace(/\s/g,'').match(/挂牌价[格]?([0-9]+(?:\.[0-9]+)?)以上/);if(!threshold||!footerText.includes('优惠5角5'))throw Error('底部说明不是“挂牌价优惠5角5”，或文字不清楚。为避免改错，已停止出图。');
 progress(90,'正在重新排版…');const ratio=w/1564;const margin=18*ratio,rowHeight=64*ratio,font=38*ratio,focusFont=46*ratio,priceHeight=54*ratio;let y=bands[0].y;const layout=result.groups.map(b=>{const first=b.stations[0];const longFirst=first?.highlight&&(first.target===0||(rules[first.rule]?.name.length||0)>12);const cells=b.stations.map((s,i)=>{const row=Math.floor(i/3),col=i%3;const widths=row===0&&longFirst?[.44,.28,.28]:[1/3,1/3,1/3];return {station:s,row,left:widths.slice(0,col).reduce((a,v)=>a+v,0),width:widths[col]};});const inlinePrice=cells.length===1&&!longFirst;const height=Math.ceil(cells.length/3)*rowHeight+(inlinePrice?0:priceHeight)+margin;return {...b,cells,inlinePrice,y:(y+=height)-height,height};});const tailHeight=input.height-tailStart;const exportScale=Math.max(1,Math.min(2,2560/w));const out=make(w*exportScale,(y+tailHeight)*exportScale);const ctx=out.getContext('2d');ctx.scale(exportScale,exportScale);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='white';ctx.fillRect(0,0,w,y+tailHeight);ctx.drawImage(input,0,0,w,bands[0].y,0,0,w,bands[0].y);
 await ensureExportFont();
 const drawFit=(text,x,y,max,size,bold=false,color='#111',align='center')=>{ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.font=`700 ${size}px "${EXPORT_FONT}"`;while(ctx.measureText(text).width>max&&size>12){size-=.5;ctx.font=`700 ${size}px "${EXPORT_FONT}"`;}ctx.fillText(text,x,y);};
 // Draw copied station glyphs over the new background to retain original spelling.
 const glyph=s=>{const b=s.box,pad=2,x=Math.max(0,b.x-pad),y=Math.max(0,b.y-pad),gw=Math.min(w-x,b.w+pad*2),gh=Math.min(input.height-y,b.h+pad*2),c=make(gw,gh),cx=c.getContext('2d');cx.drawImage(input,x,y,gw,gh,0,0,gw,gh);const pix=cx.getImageData(0,0,gw,gh);for(let i=0;i<pix.data.length;i+=4){const alpha=inkCoverage(pix.data[i],pix.data[i+1],pix.data[i+2],s.background);pix.data[i]=pix.data[i+1]=pix.data[i+2]=0;pix.data[i+3]=alpha;}cx.putImageData(pix,0,0);return c;};
 for(const b of layout){ctx.fillStyle=`rgb(${b.color.join(',')})`;ctx.fillRect(0,b.y,w,b.height);b.cells.forEach(({station:s,left,width,row})=>{const x=(left+width/2)*w,cy=b.y+margin/2+(row+.5)*rowHeight;if(s.highlight&&s.target>=0)drawFit(TARGETS[s.target],x,cy,width*w-30*ratio,focusFont,true,'#d00e16');else{const c=glyph(s);if(s.highlight){const gc=c.getContext('2d');gc.globalCompositeOperation='source-in';gc.fillStyle='#d00e16';gc.fillRect(0,0,c.width,c.height);}const sc=Math.min((s.highlight?focusFont:font)/c.height,(width*w-30*ratio)/c.width);if(s.highlight){for(const dx of [-.65,0,.65])for(const dy of [-.65,0,.65])ctx.drawImage(c,x-c.width*sc/2+dx*ratio,cy-c.height*sc/2+dy*ratio,c.width*sc,c.height*sc);}else ctx.drawImage(c,x-c.width*sc/2,cy-c.height*sc/2,c.width*sc,c.height*sc);}});drawFit(`优惠${(b.discount/100).toFixed(2)}元，结算价${(b.price/100).toFixed(2)}`,b.inlinePrice?w*2/3:w/2,b.inlinePrice?b.y+margin/2+rowHeight/2:b.y+b.height-priceHeight/2,b.inlinePrice?w*2/3-30*ratio:w-30*ratio,35*ratio,true);}
 ctx.drawImage(input,0,tailStart,w,tailHeight,0,y,w,tailHeight);const footerY=y+footerRow.y-tailStart;ctx.fillStyle=`rgb(${footerRegion.color.join(',')})`;ctx.fillRect(0,footerY-4*ratio,w,out.height-footerY+4*ratio);drawFit(`挂牌价格${threshold[1]}以上的，挂牌价优惠4角5`,w/2,footerY+(footerRow.end-footerRow.y)/2,w-32*ratio,33*ratio,true);
 progress(100,'处理完成');return {canvas:out,updates:result.updates,merged:result.merged,originalBandCount:bands.length,stationCount:stations.length,missing:result.missing,highlighted:result.highlighted};
}

